export enum AppColor {
  PRIMARY_BG,
  SECONDARY_BG,
  PRIMARY_TEXT_COLOR,
  SECONDARY_TEXT_COLOR,
  BUDGET_TEXT_COLOR,
  BUDGET_BAR_UNFILLED,
  NEUTRAL_BORDER,
  PRIMARY_CTA_COLOR,
  SECONDARY_CTA_COLOR,
  PRIMARY_TAB_CTA_COLOR,
  SECONDARY_TAB_CTA_COLOR,
  CARD_BG,
  AMT_TEXT_COLOR,
  PROGRESS_BAR_UNFILLED,
  PROGRESS_BAR_FILLED,
  PILL_DEFAULT,
  PILL_PRESSED,
  TAB_BG,
  PRIMARY_CAT_COLOR,
}

export type AppColorStrings = keyof typeof AppColor
