import { IconMap } from '../components/icon/icon-map'

export type IconMapKeyType = keyof typeof IconMap

export const CATEGORY_ICONS: Array<IconMapKeyType> = [
  'bill',
  'education',
  'entertainment',
  'food',
  'fuel',
  'groceries',
  'healthcare',
  'investment',
  'shopping',
  'transport',
  'loan',
  'gift',
  'donate',
  'bike',
  'car',
  'maintenance',
  'appliances',
  'gym',
  'machine',
  'beauty',
  'homeCategory',
  'bank',
  'religion',
  'fashion',
  'sports',
  'plant',
  'water',
  'fire',
  'electricity',
  'internet',
  'pet',
  'phone',
  'school',
  'schoolKit',
  'tax',
]
